# Generated by Django 5.1.4 on 2025-02-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="foto",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
