# Generated by Django 5.1.4 on 2025-02-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0002_material_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="foto",
            field=models.ImageField(upload_to=""),
        ),
    ]
