# Generated by Django 5.1.4 on 2025-02-05 03:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0003_alter_material_foto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="foto",
        ),
    ]
