# Generated by Django 5.1.4 on 2025-02-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0004_remove_material_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="foto",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
