# Generated by Django 6.0.5 on 2026-05-18 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventario",
            "0006_categoria_configuracion_venta_alter_material_foto_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Seccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="material",
            name="suministrador",
        ),
        migrations.RemoveField(
            model_name="orden",
            name="suministrador",
        ),
        migrations.RemoveField(
            model_name="material",
            name="categoria",
        ),
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos",
                to="inventario.categoria",
            ),
        ),
        migrations.AddField(
            model_name="categoria",
            name="seccion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias",
                to="inventario.seccion",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="seccion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos",
                to="inventario.seccion",
            ),
        ),
        migrations.DeleteModel(
            name="Suministrador",
        ),
    ]
